config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("todo_list.urls", namespace="todo"))
]

todo_list/urls.py
from django.urls import path, include

from todo_list.views import (
    TaskListView,
    TagListView,
    TagCreateView,
    TagUpdateView,
    TagDeleteView,
    TaskCreateView,
    TaskUpdateView,
    TaskDeleteView,
    CompleteUndoView
)

app_name = "todo"

urlpatterns = [
    path("", TaskListView.as_view(), name="task-list"),
    path("create/", TaskCreateView.as_view(), name="task-create"),
    path("<int:pk>/update/", TaskUpdateView.as_view(), name="task-update"),
    path("<int:pk>/delete/", TaskDeleteView.as_view(), name="task-delete"),
    path("<int:pk>/complete-undo/", CompleteUndoView.as_view(), name="complete-undo"),
    path("tags/", TagListView.as_view(), name="tag-list"),
    path("tags/create/", TagCreateView.as_view(), name="tag-create"),
    path("tags/<int:pk>/update/", TagUpdateView.as_view(), name="tag-update"),
    path("tags/<int:pk>/delete/", TagDeleteView.as_view(), name="tag-delete"),
]

todo_list/models.py
from django.db import models

class Task(models.Model):
    content = models.CharField(max_length=128)
    date = models.DateTimeField(auto_now_add=True)
    deadline = models.DateTimeField(null=True)
    status = models.BooleanField()
    tags = models.ManyToManyField(to="Tag", related_name="tasks")

    class Meta:
        ordering = ["status", "date"]

    def __str__(self):
        return f"{self.content} (Done: {self.status})"


class Tag(models.Model):
    name = models.CharField(max_length=64, unique=True)

    def __str__(self):
        return self.name

todo_list/forms.py
from django import forms

from todo_list.models import Tag, Task


class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = "__all__"
        widgets = {
            "deadline": forms.DateTimeInput(attrs={"type": "datetime-local"}),
            "tags": forms.CheckboxSelectMultiple()
        }

todo_list/views.py
from django.shortcuts import redirect, get_object_or_404, render
from django.urls import reverse_lazy, reverse
from django.views import generic

from todo_list.forms import TaskForm
from todo_list.models import Task, Tag


class TaskListView(generic.ListView):
    model = Task
    template_name = "todo_list/task_list.html"
    context_object_name = "tasks"


class TaskCreateView(generic.CreateView):
    model = Task
    template_name = "todo_list/task_form.html"
    context_object_name = "form"
    success_url = reverse_lazy("todo:task-list")
    form_class = TaskForm


class TaskUpdateView(generic.UpdateView):
    model = Task
    template_name = "todo_list/task_form.html"
    context_object_name = "form"
    success_url = reverse_lazy("todo:task-list")
    form_class = TaskForm


class TaskDeleteView(generic.DeleteView):
    model = Task
    template_name = "todo_list/delete_confirm.html"
    success_url = reverse_lazy("todo:task-list")


class CompleteUndoView(generic.ListView):
    def get(self, request, *args, **kwargs):
        task = get_object_or_404(Task, id=kwargs["pk"])
        if task.status:
            task.status = False
        else:
            task.status = True
        task.save()
        res = reverse("todo:task-list")
        return redirect(res)


class TagListView(generic.ListView):
    model = Tag
    template_name = "todo_list/tags_list.html"
    context_object_name = "tags"


class TagCreateView(generic.CreateView):
    model = Tag
    template_name = "todo_list/tag_form.html"
    context_object_name = "form"
    fields = "__all__"
    success_url = reverse_lazy("todo:tag-list")


class TagUpdateView(generic.UpdateView):
    model = Tag
    template_name = "todo_list/tag_form.html"
    context_object_name = "form"
    fields = "__all__"
    success_url = reverse_lazy("todo:tag-list")


class TagDeleteView(generic.DeleteView):
    model = Tag
    template_name = "todo_list/delete_confirm.html"
    success_url = reverse_lazy("todo:tag-list")

templates/base/base.html
<!DOCTYPE "html">
<html lang="en">
  <head>
    {% block title %}
      <title>Todo List</title>
    {% endblock %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css"
          integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
  </head>
  <body>
    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-3">
          {% block sidebar %}
            {% include "includes/sidebar.html" %}
          {% endblock %}
        </div>
        <div class="col-sm-9">
          {% block content %}
          {% endblock %}
        </div>
      </div>
    </div>
</body>
</html>   

templates/includes/sidebar.html
<ul class="sidebar-nav list-group">
  <li class="list-group-item">
    <a href="{% url 'todo:task-list' %}">Home</a>
  <li class="list-group-item">
    <a href="{% url 'todo:tag-list' %}">All Tags</a>
  </li>
</ul>

templates/todo_list/delete_confirm.html
{% extends "base/base.html" %}
{% block content %}
  {% if tag %}
    <h1>Delete Tag</h1>
    <p>Are you sure you want to delete the tag: {{ tag }}?</p>
  {% elif task %}
    <h1>Delete task</h1>
    <p>Are you sure you want to delete the task: {{ task }}?</p>
  {% endif %}
  <form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="Yes, delete" class="btn btn-danger">
  </form>
{% endblock %}

templates/todo_list/tag_form.html
{% extends "base/base.html" %}
{% load crispy_forms_filters %}
{% block content %}
  <h1>{{ object|yesno:"Update,create" }} Tag</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}
    <input class="btn btn-primary" type="submit" value="Submit">
  </form>
{% endblock %}

templates/todo_list/tags_list.html
{% extends "base/base.html" %}
{% load object_filters %}
{% block content %}
  <h1>Tags<a style="float: right" class="btn btn-primary" href="{% url 'todo:tag-create' %}">Add tag</a></h1>
  <ul class="sidebar-nav list-group mt-3">
    {% if tags %}
      <table class="table">
        <tr>
          <th>Name</th>
          <th>Update</th>
          <th>Delete</th>
        </tr>
        {% for tag in tags %}
          <tr>
            <td>{{ tag.name }}</td>
            <td><a href="{% url 'todo:tag-update' tag.id %}" class="btn btn-secondary">Update</a></td>
            <td><a href="{% url 'todo:tag-delete' tag.id %}" class="btn btn-secondary">Delete</a></td>
          </tr>
        {% endfor %}
      </table>
    {% endif %}
  </ul>
{% endblock %}

templates/todo_list/task_form.html
{% extends "base/base.html" %}
{% load crispy_forms_filters %}
{% block content %}
  <h1>{{ object|yesno:"Update,create" }} Task</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}
    <input class="btn btn-primary" type="submit" value="Submit">
  </form>
{% endblock %}

templates/todo_list/task_list.html
{% extends "base/base.html" %}
{% load object_filters %}
{% block content %}
  <h1>TODO list<a style="float: right" class="btn btn-primary" href="{% url 'todo:task-create' %}">Add task</a></h1>
  <ul class="sidebar-nav list-group mt-3">
    {% for task in tasks %}

      <li class="list-group-item">
        <h2>{{ task.content }}
          {% if task.status %}
            <span class="text-success">Done</span>
            <a style="float: right" class="btn btn-secondary mt-3" href="{% url 'todo:complete-undo' task.id %}"
            >Undo</a>
          {% else %}
            <span class="text-danger">Not done</span>
            <a style="float: right" class="btn btn-success mt-3"
               href="{% url 'todo:complete-undo' task.id %}">Complete</a>
          {% endif %}
        </h2>
        <p>Created: {{ task.date }}</p>
        <h5>
          Tags: {{ task|join_tags }}
          <a href="{% url 'todo:task-update' task.id %}">Update</a>
          <a href="{% url 'todo:task-delete' task.id %}">Delete</a>
          {% if task.deadline %}
            <span class="text-danger">Deadline: {{ task.deadline }}</span>
          {% endif %}
        </h5>
      </li>
      
    {% endfor %}
  </ul>
{% endblock %}